### ISSUE TITLE
Create pydelhi.org/conference page

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/conference#1]
It would also be preferable to have  http://PyDelhiConference.org pointing to the same page above.

**Comment by CuriousLearner** [comment]
@theskumar @akshayaurora Would this conference page would be using a parallax effect as in most of the sites related to conferences?

Also, please let me know if there are any limitations for any framework to be used/ other useful info.

**Comment by theskumar** [comment]
1. Parallax effect is nice to have, but I would avoid it if possible as it puts a lot of design limitations in terms of flexibility and scalability. 
2. There is no limitation on framework, but a Python tool like pelican/django is preferred if it's need is felt.

**Comment by CuriousLearner** [comment]
@theskumar Okay. I would like to take this up. But I think that we should have a wire-frame of what we are supposed to make. That would help new contributors as well.

**Comment by theskumar** [comment]
The site is currently hosted at https://conference.pydelhi.org, closing this now.
