### ISSUE TITLE
Add microsft logo in sponsor section

### ISSUE THREAD

**Issue by rajataaron** [pydelhi/conference#102]
Microsoft Logo to be added in sponsor section.

**Comment by CuriousLearner** [comment]
@rajataaron would you like to pick this up and put up a logo?

**Comment by rajataaron** [comment]
I have created a PR for this. Check it.

**Comment by CuriousLearner** [comment]
@rajataaron Please check review, and it would be really great if you mention in your commit message about the issue you're working on. That way it is automatically linked with your PR and closed once the PR reaches a final state.

**Comment by CuriousLearner** [comment]
Closing this.
