### ISSUE TITLE
Change current Website to update dates & other details for 2023

### ISSUE THREAD

**Issue by akshayaurora** [pydelhi/conference#130]
- [x] Change Dates
- [x] Remove schedule with Empty/"Coming soon".
- [x] #134
- [x] #135
- [x] #136
- [x] Setup CFP backend.

**Comment by pnijhara** [comment]
@akshayaurora this issue can be broken as more than 1 issue. For example, setting up the CFP backend can go as a separate issue.
I can work on changing dates, removing schedules with empty/TBA and linking to the sponsorship prospectus.
We can then choose a new colour theme in a new theme.

**Comment by stalwart201** [comment]
I will push the changes @pnijhara i'm done with them. Post it we can create seperate issues for future task.

**Comment by stalwart201** [comment]
Will open seperate issues for rest items.

**Comment by stalwart201** [comment]
For CFP will be using callpaper.io

cc: @akshayaurora
