### ISSUE TITLE
Link to updated sponsorship prospectus.

### ISSUE THREAD

**Issue by stalwart201** [pydelhi/conference#134]

**Comment by akshayaurora** [comment]
https://docs.google.com/document/d/1Pkx9Jql9Em1A_kKIgC_Z3Oxnt3QNMYqmd-8pw8wfR-0/edit

**Comment by pulsar17** [comment]
https://drive.google.com/file/d/1T1mSnLxYga3rLdDpJEVBiiOcDYhpxf2F/view?usp=sharing

@akshayaurora please have a look at this proposal. If needed, I can make a similar one for PyDelhiConf
