### ISSUE TITLE
Use scraping to get past meetups data

### ISSUE THREAD

**Issue by progmatic-99** [pydelhi/conference#141]
URL: https://www.meetup.com/pydelhi/events/
Data like-
- [ ]  Location
- [ ] No. of attendees
- [ ] Date

Format:- 
```
{
  "meetups": [
   {
     "date":  "",
       "location": "lat-long",
       "no_of_attendees": 34
    },
     ....
   ]
}
```

Use any library of your choice

**Comment by miphilomath** [comment]
This might be helpful to scrape the data: https://www.meetup.com/api/guide/

**Comment by Delta456** [comment]
I will be working on this issue.

**Comment by akshayaurora** [comment]
Data was provided and updated on sponsorship prospectus. @Delta456 thanks.
