### ISSUE TITLE
Move the Current Branch to the new branch `previous-websites` to make the old websites archive.

### ISSUE THREAD

**Issue by Mr-Sunglasses** [pydelhi/conference#156]
Move the Current Branch to the new branch `previous-websites` to make the old websites archive.

**Comment by Mr-Sunglasses** [comment]
@Animesh-Ghosh Can you do this please so that we can start up with the clean project structure.

**Comment by Animesh-Ghosh** [comment]
@Mr-Sunglasses if I do that right now, the site that's up right now might not have any details. Please feel free to replace the static content in your branch and work on the redesign.

**Comment by akshayaurora** [comment]
You should never work on this repo directly. Fork it, work on your own fork; make a pr from that fork.
