### ISSUE TITLE
[explara] registration and pricing

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/conference#16]
- [x] replace registration form with link to explara.
- [x] fetch pricing details dynamically from explara / remove the section.
- [x] number of tickets left should be fetched from explara / not mentioned statically.
- [ ] get account details of the official explara account of pssi.

**Comment by theskumar** [comment]
Here is the link: https://in.explara.com/e/pydelhi-conference

**Comment by CuriousLearner** [comment]
Link to explara added

**Comment by CuriousLearner** [comment]
The no. of tickets available are now fetched dynamically from explara

**Comment by CuriousLearner** [comment]
Pricing section is removed.

**Comment by CuriousLearner** [comment]
I think this is completed now? @bhanuvrat

**Comment by bhanuvrat** [comment]
@CuriousLearner indeed.
closing it now.
