### ISSUE TITLE
logo realted nuances

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/conference#18]
the logo currently says Pydelhi conf 
quite a small, and maybe insignificant issue, IMO it should be one of

PyDelhiConf, pure camelcase.
pyDelhiConf, like our hashtag

suggestions welcome.

**Comment by theskumar** [comment]
Updated logo at #28

**Comment by CuriousLearner** [comment]
I think this is already resolved, so closing it.

Please re-open if needed. @theskumar @bhanuvrat
