### ISSUE TITLE
"Buy Ticket" button not properly visible on desktop

### ISSUE THREAD

**Issue by specbeck** [pydelhi/conference#196]
The two buttons get hidden behind the event-info bar on full-screen desktop window.  
![Sample Picture](https://github.com/pydelhi/conference/assets/98754084/ef6154ac-6ced-4243-9bd0-d47014fdc843)

**Comment by Animesh-Ghosh** [comment]
Hi @specbeck, could you please share which resolution you are on?

**Comment by specbeck** [comment]
@Animesh-Ghosh: Sure, I'm at [1366 × 768]

**Comment by Animesh-Ghosh** [comment]
@specbeck I'm also on the same resolution but I couldn't reproduce it. Will still go ahead and merge it since it will most likely improve visibility of the Buy Ticket button for more people.

**Comment by Animesh-Ghosh** [comment]
Thanks @specbeck for the contribution. I hope I'll be able to see you at the Conf too! 🚀

**Comment by specbeck** [comment]
@Animesh-Ghosh Sure thing, super excited for the same!
