### ISSUE TITLE
Decrease initial loading time

### ISSUE THREAD

**Issue by rajat404** [pydelhi/conference#4]
The site currently takes nearly 20 seconds to load, for the first time, on a 60KB/s connection. If possible, loading time should be reduced.

**Comment by theskumar** [comment]
remove the loader, it's useless. the page should be visible as it loads progressively?

**Comment by akshayaurora** [comment]
+1 loader should be removed.

**Comment by rajat404** [comment]
The page loads quickly enough now. So closing this issue.

**Comment by CuriousLearner** [comment]
I'm working on this. Currently decreasing no. of requests the web-page issues.

Currently decreased from 126 requests to 69 requests. Doing more changes.

**Comment by CuriousLearner** [comment]
Update: 

 Optimized the loading time

```
Converted JS and CSS in single file
Corrected Schedule tab 3 linking
Replaced resource links for 404 return status
Replaced Google map to static image linking to location
```

Next, would optimize images.

**Comment by CuriousLearner** [comment]
Optimized most of the images too.

Now page size reduced to 1.09MB

**Comment by shagunsodhani** [comment]
Results from PageSpeed Insights:
[https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fconference.pydelhi.org%2F&tab=desktop](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fconference.pydelhi.org%2F&tab=desktop)

**Comment by CuriousLearner** [comment]
I think since we're using single js and css file, above fold content wouldn't be prioritized.

If we want to do that, we can take the timer js and specific css out so that they load quickly. But since, we're using a loader, I think it's not necessary. Suggestions welcome.

Also, yes, I would work and try to optimize images more. Thanks.

**Comment by shagunsodhani** [comment]
We can minimize js/css as well.

**Comment by CuriousLearner** [comment]
@shagunsodhani the css and js files are minified when served.

**Comment by shagunsodhani** [comment]
:+1:
