### ISSUE TITLE
Set up a blog for conference using static site generator

### ISSUE THREAD

**Issue by CuriousLearner** [pydelhi/conference#40]
I'm working on this!

**Comment by CuriousLearner** [comment]
Update: Blog generated using Pelican. Need suggestions on themes to use. @theskumar Currently the default theme is Smashing Magazine.

Current screenshot:

![pydelhi conf blog](https://cloud.githubusercontent.com/assets/8039608/12277069/69d50054-b971-11e5-8696-2e69398c5b29.png)

**Comment by theskumar** [comment]
@CuriousLearner let's move the blog to https://github.com/pydelhi/blog and the conference is going to be just one category, called `Pydelhi Conf 2016`, which link from elsewhere as needed.

For the base setup, let's use the setup from here: https://github.com/taigaio/taiga-blog with proper attributions and modify/rename the theme as needed.

**Comment by CuriousLearner** [comment]
@theskumar okay, as discussed, it would be done.

Closing this issue here.
