### ISSUE TITLE
generate the static-site from a source of truth

### ISSUE THREAD

**Issue by bhanuvrat** [pydelhi/conference#41]
- [ ] convert index.html into a jinja template.
- [ ] build a source of truth with yaml / markdown files.
- [ ] use either a custom script / ansible to render index.html
- [ ] automate uploading the htmls to gh-pages using jinja2.
## Problems it will solve
- save time by not having to look for values to update in the html.
- less chance of errors like the conference date debacle.

**Comment by Kushagra343** [comment]
http://kushagra343.github.io/

converted index.html into jinja template.
build a source of truth with yaml 
ansible to render index.html.

**Comment by Kushagra343** [comment]
git link https://github.com/Kushagra343/kushagra343.github.io

**Comment by CuriousLearner** [comment]
Please re-open this when needed.

Closing it for now.
