### ISSUE TITLE
Add server sponsors on the page

### ISSUE THREAD

**Issue by dusual** [pydelhi/conference#51]
We have not included our server sponsors on the page. This is the basic guideline they had set out for us.

"""
We would love to have a permanent Django jobs page at the website and
a URL linkback on bottom of all pages or above the fold right column
ad of same size as running at trak.in.
"""

**Comment by satyaakam** [comment]
@dusual its there see the bottom of the page

**Comment by satyaakam** [comment]
@dusual also can you get the details of what kind of banner they want design wise and where it has to be linked to.

**Comment by satyaakam** [comment]
The banner size https://e2enetworks.com/e2enetworks.png is too big don't know how its gonna go with the design , some UI guy need to take a look and ask for exact sizes and colour combinations.

**Comment by dusual** [comment]
@satyaakam can you add that to mail thread then

**Comment by satyaakam** [comment]
No lets talk here itself so that we can come up with a standard banner sizes for others as well.

**Comment by CuriousLearner** [comment]
I think we included a link at the bottom of the conference site page. Is there something else needed, or we can close this issue?

@satyaakam @dusual

**Comment by Tusharmalik** [comment]
![step0002](https://cloud.githubusercontent.com/assets/20543745/23282481/5f98f308-fa47-11e6-97ea-0590b89a4472.png)

@satyaakam I have reduced the size of banner if this is what you are asking for

https://drive.google.com/open?id=0B6YnYVD_QMQRNTBhc3NQT1RvcnM

**Comment by CuriousLearner** [comment]
This seems resolved. Please re-open if needed.
