### ISSUE TITLE
Start adding content

### ISSUE THREAD

**Issue by CuriousLearner** [pydelhi/conference#7]
These sections are to be added with actual info:
- [x] About the conference
- [x] Event Schedule
- [x] Speakers info
- [x] Sponsors info
- [x] FAQ
- [x] Prices
- [x] Register Now section

**Comment by CuriousLearner** [comment]
Added "About Conference" and Initial event schedule for both auditoriums.

Would create a PR, once previous one is reviewed.

**Comment by theskumar** [comment]
Updated the issue as a todo list. easier to track.

**Comment by CuriousLearner** [comment]
FAQ added via #32 
Prices removed from the site
Register Now section linked to explara

**Comment by CuriousLearner** [comment]
This is completed.
